---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks: 
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=1
    - name: btcd install required dependencies
      ansible.builtin.package:
        name: "git-core"
        state: present